--- 
- hosts: meteorpi, meteorpi2, meteorpi3
  vars:
    srcdir: /mnt/c/Users/mark/Documents/Projects/meteorhunting/UKMON-shared/Pi_Cameras 
    destdir: /home/pi/mjmm
  tasks: 
  - name: Create Directory
    file:
      path: '{{destdir}}/eventlog'
      state: directory
      mode: '0755'

  - name: copy files
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - {src: '{{srcdir}}/checkForMeteors.sh', dest: '{{destdir}}', mode=0755, backup=no }
      - {src: '{{srcdir}}/latestEvents.sh', dest: '{{destdir}}', mode=0755, backup=no }
      - {src: '{{srcdir}}/postProcess.sh', dest: '{{destdir}}', mode=0755, backup=no }
      - {src: '{{srcdir}}/logTemperature.sh', dest: '{{destdir}}', mode=0755, backup=no }
      - {src: '{{srcdir}}/sendToYoutube.py', dest: '{{destdir}}', mode=0644, backup=no  }
      - {src: '{{srcdir}}/config.ini', dest: '{{destdir}}', mode=0644, backup=no  }

  - name: Replace email
    replace: 
      path: '{{destdir}}/config.ini'
      regexp: "youremail@here"
      replace: "markmcintyre99@googlemail.com"
      backup: no
